language: php

php:
  - 7.2
  - 7.3
  - 7.4

before_script:
  - composer install

script:
  - composer validate
  - phpunit
  - ./vendor/bin/php-cs-fixer fix -v --diff --dry-run --config .php_cs.php

after_success:
  - bash <(curl -s https://codecov.io/bash)
