name: Publish release to WordPress.org plugin directory when there is a new release on GitHub

on:
  # Trigger manually from https://github.com/Automattic/chatrix/actions/workflows/on-release-published.yml
  workflow_dispatch:

  release:
    types: [released]

jobs:
  call-publish-release:
    uses: ./.github/workflows/publish-release.yml
    with:
      version: ${{ github.event.release.tag_name }}
