name: PR checks

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  php-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install composer dependencies
        run: composer install

      - name: Run phpcs
        run: ./vendor/bin/phpcs

  frontend-build-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install npm dependencies
        run: yarn install

      - name: Run eslint
        run: yarn lint

      - name: Build block
        run: yarn build:block

      - name: Build popup
        run: yarn build:popup
