# Create a draft release when a tag is pushed
name: Create a release

on:
  # Allow manual trigger from the Actions tab:
  # https://github.com/Automattic/chatrix/actions/workflows/release.yml
  workflow_dispatch:

  push:
    tags: ['v*']

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build
        run: make

      - name: Create directory for release
        run: cp -r wordpress/chatrix chatrix-wordpress-plugin-${{ github.ref_name }}

      - name: Remove unnecessary files from wordpress plugin
        run: |
          rm -rf chatrix-wordpress-plugin-${{ github.ref_name }}/bin
          rm -rf chatrix-wordpress-plugin-${{ github.ref_name }}/README.md

      - name: Create archive release
        run: tar -cvzf chatrix-wordpress-plugin-${{ github.ref_name }}.tar.gz chatrix-wordpress-plugin-${{ github.ref_name }}

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          artifacts: "chatrix-wordpress-plugin-${{ github.ref_name }}.tar.gz"
          artifactErrorsFailBuild: true
          draft: true
