# Create a draft release when a tag is pushed
name: Create a release

on:
  # Allow manual trigger from the Actions tab:
  # https://github.com/Automattic/chatrix/actions/workflows/release.yml
  workflow_dispatch:

  push:
    tags: ['v*']

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install composer dependencies
        run: composer install --no-ansi --no-dev --no-interaction --no-plugins --no-scripts --optimize-autoloader

      - name: Install npm dependencies
        run: yarn install

      - name: Build frontend
        run: yarn build

      - name: Create directory for release
        run: mkdir /tmp/release

      - name: Copy all files to release directory
        run: cp -r ./* /tmp/release/

      - name: Remove unnecessary files and directories
        run: |
          rm -rf /tmp/release/.github
          rm -rf /tmp/release/.git
          rm -rf /tmp/release/.gitignore
          rm -rf /tmp/release/.editorconfig
          rm -rf /tmp/release/.eslintrc.js
          rm -rf /tmp/release/.wp-env.json
          rm -rf /tmp/release/bin
          rm -rf /tmp/release/CONTRIBUTING.md
          rm -rf /tmp/release/Makefile
          rm -rf /tmp/release/phpcs.xml
          rm -rf /tmp/release/tsconfig.json
          rm -rf /tmp/release/build/.tmp
          rm -rf /tmp/release/node_modules
          rm -rf /tmp/release/frontend
          rm -rf /tmp/release/block

      - name: Move and rename release directory
        run: mv /tmp/release chatrix

      - name: Create zip archive for release
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r chatrix-${{ github.ref_name }}.zip chatrix

      - name: Create tar archive for release
        run: tar -cvzf chatrix-${{ github.ref_name }}.tar.gz chatrix

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          artifacts: "chatrix-${{ github.ref_name }}.tar.gz,chatrix-${{ github.ref_name }}.zip"
          artifactErrorsFailBuild: true
          draft: true
